ufc-frontend/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  get '/login', to: 'sessions#login'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Routes for user registration
  post '/login', to: 'users#login'
  get '/register', to: 'users#new'
  post '/users', to: 'users#create'
  get '/thank_you', to: 'users#thank_you'

  # Admin actions
  get 'admin/users', to: 'admin#users'
  patch 'admin/users/:id', to: 'admin#update', as: 'update_user_admin_status'
  delete 'admin/users/:id', to: 'admin#destroy', as: 'delete_user'

  # Routes for votes and results
  get '/votes', to: 'votes#new'
  post '/votes', to: 'votes#create'
  get '/results', to: 'votes#results'

  # Routes for fighters
  get '/fighters', to: 'fighters#new'
  post '/fighters', to: 'fighters#create'
  get '/fighters/list', to: 'fighters#list'

  # Resources for users and fighters
  resources :users, only: %i[new create] # Only new and create actions for users
  resources :fighters, only: %i[new index] # Only index action for fighters

  if Rails.env.test?
    get 'test', to: 'test#index'
    get 'test/private_action', to: 'test#private_action'
    get 'test/admin_action', to: 'test#admin_action'
  end
end

ufc-frontend/app/views/admin/users.html.erb
<h1>Manage Users</h1>

<% if @users.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Admin Status</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user["name"] %></td>
          <td><%= user["email"] %></td>
          <td><%= user["is_admin"] ? "Yes" : "No" %></td>
          <td>
          <%= form_with url: update_user_admin_status_path(user['id']), method: :patch, local: true, data: { turbo: false } do %>
           <%= submit_tag user["is_admin"] ? "Remove Admin" : "Make Admin" %>
          <% end %>
          <%= form_with url: delete_user_path(user['id']), method: :delete, local: true, data: { confirm: "Are you sure?", turbo: false }, class: "btn btn-danger" do %>
           <%= submit_tag "Delete User" %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No users found.</p>
<% end %>

<h1>Infastruture</h1>
<h2>Monitoring</h2>
<ul>
  <li><a href="http://localhost:9090" target="_blank">Prometheus Dashboard</a></li>
  <li><a href="http://localhost:3000" target="_blank">Grafana Dashboard</a></li>
</ul>
<h2>Services</h2>
<ul>
  <li><a href="http://localhost:3001" target="_blank">User API</a></li>
  <li><a href="http://localhost:3002" target="_blank">Voting API</a></li>
  <li><a href="http://localhost:3005" target="_blank">Frontend Blue</a></li>
  <li><a href="http://localhost:3006" target="_blank">Frontend Green</a></li>
</ul>